name: Primer workflow

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest


    steps:
      - name: Mostar mensaje
        run: echo "Hola GH Actions"
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 main.py
